swagger: '2.0'
info:
  description: This service is in charge to handle articles 
  version: 0.0.1
  title: Articles Service
host: manager-demov3.sensedia.com
basePath: /articles-service/
tags:
  - name: Articles
    description: Article domain
schemes:
  - https
  - http
paths:
  /v1/articles:
    post:
      summary: Saves a new article to be published
      tags:
        - Articles
      parameters:
        - in: "header"
          name: "client_id"
          description: client id that identify the consumer
          required: true
          type: "string"
        - in: header
          name: access_token
          description: access token
          required: true
          type: string
        - name: "PostArticle"
          in: "body"
          required: true
          schema:
            $ref: '#/definitions/PostArticles'
      responses:
        '201':
          description: Created.
        '400':
          description: Bad Request.
        '401':
          description: "Authentication error"
        '403':
          description: "Authorization error"
        '404':
          description: "Resource not found"
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/_businessErrorMessage'
        '500':
          description: "Internal server error"
        '503':
          description: "Unavailable server error"
        '504':
          description: "Max server limmit reached"
  /v1/{articleId}/articles:          
    delete:
      tags:
        - Articles
      summary: Inativate an article
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: client_id
          in: header
          description: Client id.
          required: true
          type: string
        - name: access_token
          in: header
          description: Access token.
          required: true
          type: string
        - name: articleId
          in: path
          required: true
          type: string
          description: Id of the article
      responses:
        '202':
          description: Accepted.
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/_businessErrorMessage'
        '500':
          description: Internal Server Error.
    get:
      tags:
        - Articles
      summary: Query article by ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: client_id
          in: header
          description: Client id.
          required: true
          type: string
        - name: access_token
          in: header
          description: Access token.
          required: true
          type: string
        - name: articleId
          in: path
          required: true
          type: string
          description: Id of the article
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/GetArticles'
    
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.
        '412':
          description: Pre-condition Failed.
          schema:
            type: array
            items:
              $ref: '#/definitions/_businessErrorMessage'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/_businessErrorMessage'
        '500':
          description: Internal Server Error.
definitions:
  _businessErrorMessage:
    type: object
    properties:
      code:
        type: string
        description: Error code.
      message:
        type: string
        description: Error message.
  PostArticles: 
    type: object
    properties:
      title:
        type: string
        description: Name of the article
      type:
        enum:
          - HEALTH
          - SPORTS
          - POLITICS
        description: Type of the article that was created
      summary:
        type: string
        description: a little summary of the article
      content:
        type: string
        description: The article content
      price:
        type: number
        description: The base price of the article
        example: 10.00
      date:
        type: string
        format: date
        description: The date of the article
      author:
        type: string
        description: The author or authors of the article
    required: 
      - title
      - type
      - summary
      - content
      - price
      - date
      - author
  GetArticles:
    type: object
    properties:
      id:
        type: string
        description: The unique identification of an article
      title:
        type: string
        description: Name of the article
      type:
        enum:
          - HEALTH
          - SPORTS
          - POLITICS
        description: Type of the article that was created
      summary:
        type: string
        description: a little summary of the article
      content:
        type: string
        description: The article content
      price:
        type: number
        description: The base price of the article
        example: 10.00
      date:
        type: string
        format: date
        description: The date of the article
      author:
        type: string
        description: The author or authors of the article